-- SUPABASE SCHEMA DEFINITION: WOW SALON ADMIN V2 (PRODUCTION READY)
-- Execute this entire script in the Supabase SQL Editor.

--------------------------------------------------------
-- 1. DROP EXISTING TABLES & TYPES
--------------------------------------------------------
DROP TABLE IF EXISTS public.staff_commissions CASCADE;
DROP TABLE IF EXISTS public.visit_products CASCADE;
DROP TABLE IF EXISTS public.visit_services CASCADE;
DROP TABLE IF EXISTS public.appointment_services CASCADE;
DROP TABLE IF EXISTS public.appointments CASCADE;
DROP TABLE IF EXISTS public.customer_visits CASCADE;
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.staff CASCADE;
DROP TABLE IF EXISTS public.services CASCADE;
DROP TABLE IF EXISTS public.customer_rewards CASCADE;
DROP TABLE IF EXISTS public.package_services CASCADE;
DROP TABLE IF EXISTS public.packages CASCADE;
DROP TABLE IF EXISTS public.customers CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

DROP TYPE IF EXISTS public.user_role CASCADE;

--------------------------------------------------------
-- 2. CREATE ENUMS, EXTENSIONS & TRIGGERS
--------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE public.user_role AS ENUM ('Owner', 'Manager', 'Receptionist');

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

--------------------------------------------------------
-- 3. CREATE PROFILES TABLE & HELPER FUNCTIONS
--------------------------------------------------------

-- Profiles (Linked to auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  role public.user_role NOT NULL DEFAULT 'Receptionist',
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'Owner'); -- Defaulting to Owner for now, adjust if needed
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger the function every time a user is created
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- These helper functions allow RLS policies to easily check the user's role without recursive queries.
CREATE OR REPLACE FUNCTION public.is_owner() RETURNS BOOLEAN AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'Owner');
$$ LANGUAGE sql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_manager() RETURNS BOOLEAN AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Owner', 'Manager'));
$$ LANGUAGE sql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_receptionist() RETURNS BOOLEAN AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Owner', 'Manager', 'Receptionist'));
$$ LANGUAGE sql SECURITY DEFINER;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Owner can view all profiles" ON public.profiles FOR SELECT USING (public.is_owner());
CREATE POLICY "Owner can update profiles" ON public.profiles FOR UPDATE USING (public.is_owner());

--------------------------------------------------------
-- 4. CREATE CORE ENTITY TABLES
--------------------------------------------------------
-- Customers Table
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    dob DATE,
    services_taken TEXT[],
    products_bought TEXT[],
    staff_served TEXT[],
    amount_paid NUMERIC DEFAULT 0,
    notes TEXT,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_customers_updated_at BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.customers FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow insert for all staff" ON public.customers FOR INSERT WITH CHECK (public.is_receptionist());
CREATE POLICY "Allow update for all staff" ON public.customers FOR UPDATE USING (public.is_receptionist());
CREATE POLICY "Allow delete for Owner and Manager" ON public.customers FOR DELETE USING (public.is_manager());

-- Customer Rewards
CREATE TABLE public.customer_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    points INTEGER DEFAULT 0,
    membership_tier TEXT DEFAULT 'Standard',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_rewards_updated_at BEFORE UPDATE ON public.customer_rewards FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.customer_rewards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.customer_rewards FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow insert/update for Manager" ON public.customer_rewards FOR ALL USING (public.is_manager());

-- Services Table
CREATE TABLE public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Other',
    price NUMERIC NOT NULL DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_services_updated_at BEFORE UPDATE ON public.services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.services FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow edit for Manager" ON public.services FOR ALL USING (public.is_manager());

-- Packages
CREATE TABLE public.packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_packages_updated_at BEFORE UPDATE ON public.packages FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.packages FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow edit for Manager" ON public.packages FOR ALL USING (public.is_manager());

-- Package Services Mapping
CREATE TABLE public.package_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT REFERENCES public.packages(id) ON DELETE CASCADE,
    service_id BIGINT REFERENCES public.services(id) ON DELETE CASCADE
);
ALTER TABLE public.package_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.package_services FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow edit for Manager" ON public.package_services FOR ALL USING (public.is_manager());

-- Staff Table
CREATE TABLE public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    gender TEXT,
    salary NUMERIC DEFAULT 0,
    commission_rate NUMERIC DEFAULT 10, -- Default 10%
    service_revenue NUMERIC DEFAULT 0,
    commission_earned NUMERIC DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_staff_updated_at BEFORE UPDATE ON public.staff FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.staff FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow edit for Manager" ON public.staff FOR ALL USING (public.is_manager());

-- Products (Inventory) Table
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    purchase_price NUMERIC NOT NULL DEFAULT 0,
    selling_price NUMERIC NOT NULL DEFAULT 0,
    purchased_quantity INTEGER NOT NULL DEFAULT 0,
    sold_quantity INTEGER NOT NULL DEFAULT 0,
    salon_consumption INTEGER NOT NULL DEFAULT 0,
    current_stock INTEGER NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    low_stock_threshold INTEGER NOT NULL DEFAULT 5,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.products FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow insert/update for Manager" ON public.products FOR INSERT WITH CHECK (public.is_manager());
CREATE POLICY "Allow update for Manager" ON public.products FOR UPDATE USING (public.is_manager());
CREATE POLICY "Allow delete for Owner" ON public.products FOR DELETE USING (public.is_owner());

-- Expenses Table
CREATE TABLE public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    title TEXT,
    category TEXT NOT NULL CHECK (category IN ('Electricity', 'Water', 'Rent', 'Internet', 'Salary', 'Inventory', 'Other Expenses')),
    amount NUMERIC NOT NULL DEFAULT 0,
    payment_method TEXT DEFAULT 'Cash',
    status TEXT DEFAULT 'Paid',
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_expenses_updated_at BEFORE UPDATE ON public.expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owner read access" ON public.expenses FOR SELECT USING (public.is_owner());
CREATE POLICY "Manager read access" ON public.expenses FOR SELECT USING (public.is_manager());
CREATE POLICY "Manager insert access" ON public.expenses FOR INSERT WITH CHECK (public.is_manager());
CREATE POLICY "Manager update access" ON public.expenses FOR UPDATE USING (public.is_manager());
CREATE POLICY "Owner delete access" ON public.expenses FOR DELETE USING (public.is_owner());

--------------------------------------------------------
-- 5. CREATE TRANSACTION & MAPPING TABLES
--------------------------------------------------------

-- Customer Visits (Master Transaction Record)
CREATE TABLE public.customer_visits (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    visit_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    service_total NUMERIC DEFAULT 0,
    product_total NUMERIC DEFAULT 0,
    grand_total NUMERIC DEFAULT 0,
    original_total NUMERIC DEFAULT 0,
    discount_amount NUMERIC DEFAULT 0,
    payment_method TEXT DEFAULT 'Cash',
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE SET NULL,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_visits_updated_at BEFORE UPDATE ON public.customer_visits FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.customer_visits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.customer_visits FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow insert for all staff" ON public.customer_visits FOR INSERT WITH CHECK (public.is_receptionist());
CREATE POLICY "Allow update for all staff" ON public.customer_visits FOR UPDATE USING (public.is_receptionist());
CREATE POLICY "Allow delete for Owner" ON public.customer_visits FOR DELETE USING (public.is_owner());

-- Appointments
CREATE TABLE public.appointments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT,
    appointment_date TIMESTAMP WITH TIME ZONE NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'scheduled',
    payment_due NUMERIC DEFAULT 0,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE SET NULL,
    is_deleted BOOLEAN DEFAULT false,
    converted_visit_id UUID REFERENCES public.customer_visits(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_appointments_updated_at BEFORE UPDATE ON public.appointments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for staff" ON public.appointments FOR ALL USING (public.is_receptionist());

-- Appointment Services
CREATE TABLE public.appointment_services (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    appointment_id UUID REFERENCES public.appointments(id) ON DELETE CASCADE,
    service_id BIGINT REFERENCES public.services(id) ON DELETE SET NULL,
    service_name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0
);
ALTER TABLE public.appointment_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for staff" ON public.appointment_services FOR ALL USING (public.is_receptionist());

-- Visit Services Mapping
CREATE TABLE public.visit_services (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    service_id BIGINT REFERENCES public.services(id) ON DELETE SET NULL,
    service_name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0
);
ALTER TABLE public.visit_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for staff" ON public.visit_services FOR ALL USING (public.is_receptionist());

-- Visit Products Mapping
CREATE TABLE public.visit_products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price NUMERIC NOT NULL DEFAULT 0
);
ALTER TABLE public.visit_products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for staff" ON public.visit_products FOR ALL USING (public.is_receptionist());

-- Staff Commissions Table
CREATE TABLE public.staff_commissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    service_amount NUMERIC NOT NULL DEFAULT 0,
    commission_amount NUMERIC NOT NULL DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_commissions_updated_at BEFORE UPDATE ON public.staff_commissions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.staff_commissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Manager read access" ON public.staff_commissions FOR SELECT USING (public.is_manager());
CREATE POLICY "Staff all access" ON public.staff_commissions FOR ALL USING (public.is_receptionist()); -- Needs insert/update for visits

--------------------------------------------------------
-- 6. CREATE INDEXES FOR PERFORMANCE
--------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_name ON public.customers(name);
CREATE INDEX IF NOT EXISTS idx_customers_is_deleted ON public.customers(is_deleted);

CREATE INDEX IF NOT EXISTS idx_visits_date ON public.customer_visits(visit_date);
CREATE INDEX IF NOT EXISTS idx_visits_customer_id ON public.customer_visits(customer_id);
CREATE INDEX IF NOT EXISTS idx_visits_staff_id ON public.customer_visits(staff_id);
CREATE INDEX IF NOT EXISTS idx_visits_is_deleted ON public.customer_visits(is_deleted);

CREATE INDEX IF NOT EXISTS idx_visit_services_visit_id ON public.visit_services(visit_id);
CREATE INDEX IF NOT EXISTS idx_visit_products_visit_id ON public.visit_products(visit_id);

CREATE INDEX IF NOT EXISTS idx_commissions_staff_id ON public.staff_commissions(staff_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses(date);
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products(name);

--------------------------------------------------------
-- 7. SEED DEFAULT DATA
--------------------------------------------------------

INSERT INTO public.services (service_name, category, price) VALUES 
('Hair Cuts', 'Hair Services', 500),
('Shampoo & Conditioning', 'Hair Services', 300),
('Deep Conditioning', 'Hair Services', 800),
('Head Massage', 'Hair Services', 400),
('Hair Styling', 'Hair Services', 600),
('Hair Fall Treatment', 'Hair Treatments', 2000),
('Anti-Dandruff Treatment', 'Hair Treatments', 1800),
('Keratin Treatment', 'Hair Treatments', 4000),
('Ombre Colour', 'Hair Colour Services', 4500),
('Balayage Colour', 'Hair Colour Services', 5000),
('Botox Treatment', 'Hair Smoothing Services', 5500),
('Threading', 'Beauty Services', 100),
('Waxing', 'Beauty Services', 600),
('Bridal Makeup', 'Beauty Services', 15000),
('Facial', 'Beauty Services', 1500),
('Manicure', 'Beauty Services', 500),
('Pedicure', 'Beauty Services', 600);

INSERT INTO public.staff (name, gender, salary, commission_rate) VALUES 
('Jitendra', 'Male', 25000, 15),
('Staff 2', 'Female', 20000, 10);

--------------------------------------------------------
-- 8. ENABLE REALTIME
--------------------------------------------------------
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;

ALTER PUBLICATION supabase_realtime ADD TABLE public.customers;
